#!/bin/bash
LPCNT_AUX_PATH=./bin
$LPCNT_AUX_PATH/gringo --output smodels | $LPCNT_AUX_PATH/lp2normal2-2.27  |  $LPCNT_AUX_PATH/lp2lp2-1.23 | $LPCNT_AUX_PATH/lp2sat-1.24 | $LPCNT_AUX_PATH/runsolver-3.4.0 -M 4096 -W 360 -w /dev/null $LPCNT_AUX_PATH/d4-1.2 -mc /dev/stdin
# 4096 is main memory limit in MB
# 360 is time limit in seconds
